### ISSUE TITLE
Error when sizes are not correct.

### ISSUE THREAD

**Issue by ankitrgadiya** [Abhi2424shek/ImageSizeLinter#1]
To test it, I placed both files from lib directory in GCI 16 site local repo, and I changed the value of width and height to 100
```- directory: ./images/blogs/**/*.*
  width: 1920
  height: 1080

- directory: ./images/mentors/**/*.*
  width: 100
  height: 100
```
This is what I'm getting.
```
ankitrgadiya:~/workspace/gci16.fossasia.org (gh-pages) $ ruby ImageSizeLinter.rb 
Starting Image Checker, authored by Abishek V Ashok for FOSSASIA with love
Improvements by Robby O'Connor during GCI 2016
The image ./images/mentors/dishantkhanna.jpg is larger than 100px x 100px [w x h]
ImageSizeLinter.rb:38:in `block (2 levels) in check_images?': undefined method `valid' for #<ImageSizeLinter:0x00000001c3da88> (NoMethodError)
        from ImageSizeLinter.rb:36:in `each'
        from ImageSizeLinter.rb:36:in `block in check_images?'
        from ImageSizeLinter.rb:33:in `each'
        from ImageSizeLinter.rb:33:in `check_images?'
        from ImageSizeLinter.rb:45:in `ok?'
        from ImageSizeLinter.rb:62:in `<main>'
```

Instead it should list all the files as all files are 240x240 px. @Abhi2424shek If you remember this is the same error we were getting when I ported the code for gc15 site.

**Comment by ankitrgadiya** [comment]
okay I found out the problem. Creating PR

**Comment by Abhi2424shek** [comment]
@ankitrgadiya please see the PR #6 fixes it off
